### ISSUE TITLE
Targeting sdk 31 and above

### ISSUE THREAD

**Issue by dgjinovci** [quantum6/Android-USB-OTG-Camera#13]
If targeting sdk 31 and above, PendingIntent will cause IllegalArgumentException if last flag is not set

At: libusbcamera/src/main/java/com/serenegiant/usb/USBMonitor.java line 181

**Comment by quantum6** [comment]
Is SDK 31 is android 13? My phone is android 11.

**Comment by dgjinovci** [comment]
It's android 12

Pending intent has changed for android 12/sdk 31 and up 

https://stackoverflow.com/questions/71689781/android-app-crashes-when-targeting-to-android-12


Changes: https://developer.android.com/reference/android/app/PendingIntent?hl=en#FLAG_MUTABLE

**Comment by quantum6** [comment]
Thanks, I modified code.
Good luck!
