### ISSUE TITLE
How to apply mirror effect to the camera view?

### ISSUE THREAD

**Issue by PrasannaKBhat** [quantum6/Android-USB-OTG-Camera#15]
Hi, 

I wanted to see the mirror effect of the preview from camera. 
Could you please guide on how can we achieve the same using this library.

Thanks,
Prasanna

**Comment by PrasannaKBhat** [comment]
Thanks for the response.
Could you please provide any usage example of it.

**Comment by quantum6** [comment]
Here is my principle:
If you want some advices from me, it's free.
If you want me to modify code, pay for the work.
Good luck!
