### ISSUE TITLE
Problem on trying to install

### ISSUE THREAD

**Issue by blennerSilva** [quantum6/Android-USB-OTG-Camera#18]
i'm following your implementation tutorial but it does not work 

Could not HEAD 'https://developer.huawei.com/repo/com/serenegiant/common/4.1.1/common-4.1.1.pom'. Received status code 403 from server: Forbidden

for some reason i cant download this file even with the aar already in the project

**Comment by quantum6** [comment]
I clean the project and rebuild OK.
1, You can search the key word huawei and check it.
2, Check build.gradle for this:
        //maven { url 'http://raw.github.com/saki4510t/libcommon/master/repository/' }
        maven { url 'http://maven.aliyun.com/nexus/content/groups/public/' }
3,  Is the apk can install and work ?

Good luck
