### ISSUE TITLE
有没有碰到录制的视频会花屏的？

### ISSUE THREAD

**Issue by HuangShun** [quantum6/Android-USB-OTG-Camera#2]
红米k40

**Comment by quantum6** [comment]
不明白具体。以下哪种情形？
１、预览画面花屏？这个从来没有见过。
２、录制后的视频播放花屏？这个应该是编码过程的问题，比如帧率，保存等。

**Comment by HuangShun** [comment]
> 不明白具体。以下哪种情形？ １、预览画面花屏？这个从来没有见过。 ２、录制后的视频播放花屏？这个应该是编码过程的问题，比如帧率，保存等。

预览和拍照都没问题，但是录制完成的视频是绿色带条纹的

**Comment by quantum6** [comment]
显然是编码时的问题。猜测：
1、格式不对？
2、帧处理不当？比如丢了？
