### ISSUE TITLE
capturePictue issue

### ISSUE THREAD

**Issue by blennerSilva** [quantum6/Android-USB-OTG-Camera#21]
hii im trying to take the still picture but the provided method is not working properly, so i need some guidance here is my piece of code

![image](https://github.com/quantum6/Android-USB-OTG-Camera/assets/10924301/df9f180f-3794-4d4c-87c9-63b62ac2a656)

as you can see it finds de path properly but it does not get into the capturePicture method and does what it suppose todo

![image](https://github.com/quantum6/Android-USB-OTG-Camera/assets/10924301/cb658628-acad-4add-9cff-6588686a09c2)

**Comment by quantum6** [comment]
You can change a path to save it.
