### ISSUE TITLE
On-connect issue

### ISSUE THREAD

**Issue by ravi2611gupta** [quantum6/Android-USB-OTG-Camera#22]
When I am attaching the OTG  camera device I am not able to see the output of that camera and I have to do 2 things to see the output 
1. Restart the app
2. Select a resolution

and I want to get rid of this problem
I want that as I attach the device the output will show on my screen.

**Comment by quantum6** [comment]
I can't reduce this question.

**Comment by ravi2611gupta** [comment]
I have resolved the second problem "Select the resolution" but I am stuck in the first one  "Restarting the app".
I think it not a good UX that user have to re-start the app after granting the permission. 

I just want to resolve this issue. I just want to show the preview immediately when a user grant the permission.
I tried it but it is not working. Please let me show you the code.

` @Override
        public void onAttachDev(UsbDevice device) {
            // request open permission
            if (!isRequest) {
                isRequest = true;
                if (mCameraHelper != null) {
                    mCameraHelper.requestPermission(0);
                    isPreview = true;
                    onConnectDev(device, true);
                }
            }
        }


  @Override
        public void onConnectDev(UsbDevice device, boolean isConnected) {
            handleDeviceConnection(device, isConnected);
        }


        private void handleDeviceConnection(UsbDevice device, boolean isConnected) {
            if (!isConnected) {
                showShortMsg("fail to connect,please check resolution params");
                isPreview = false;
            } else {
                mCameraHelper.startPreview(mUVCCameraView);
                isPreview = true;
                showShortMsg("connecting");
                // initialize seekbar
                // need to wait UVCCamera initialize over
                new Thread(new Runnable() {
                    @Override
                    public void run() {
                        try {
                            Thread.sleep(2500);
                        } catch (InterruptedException e) {
                            e.printStackTrace();
                        }
                        Looper.prepare();
                        mCameraHelper.updateResolution(1280, 960);
                        if(mCameraHelper != null && mCameraHelper.isCameraOpened()) {
                            mSeekBrightness.setProgress(mCameraHelper.getModelValue(UVCCameraHelper.MODE_BRIGHTNESS));
                            mSeekContrast.setProgress(mCameraHelper.getModelValue(UVCCameraHelper.MODE_CONTRAST));
                        }
                        Looper.loop();
                    }
                }).start();
            }
        }
`

**Comment by ravi2611gupta** [comment]
please help me out it is really important. I just want to show the preview immediately when a user grants permission.
I tried it but it is not working.

**Comment by quantum6** [comment]
> please help me out it is really important. I just want to show the preview immediately when a user grants permission. I tried it but it is not working.

I really don't know how to position the problem,
I think you can check the initiate route?

**Comment by quantum6** [comment]
Good news! You can modify the USBMonitor.java(178), like this:
						//Build.VERSION.SDK_INT <= 30 ? 0 : PendingIntent.FLAG_IMMUTABLE);
						0);
