### ISSUE TITLE
Video Recording

### ISSUE THREAD

**Issue by thefaisalurrehman** [quantum6/Android-USB-OTG-Camera#4]
The video is not saving. just only save the name with mp4 extension and the file size is 0kb

**Comment by quantum6** [comment]
> 

Really? I will check the code.

**Comment by thefaisalurrehman** [comment]
> > 
> 
> Really? I will check the code.

thank

**Comment by quantum6** [comment]
I tested ant it's OK. Can you give me more info?

**Comment by quantum6** [comment]
1, Perssimion problem.
2, Save path.
